apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: kubebrowser
build:
  artifacts:
    - image: kubebrowser
      context: .
      hooks:
        before:
          - command: ["sh", "-c", "./scripts/buildFrontForBack.sh"]
            os: [darwin, linux]
      ko:
        dir: server
  local:
    push: true
